# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado projects/JZ_project_2/JZ_project_2/JZ_project_2.srcs/sources_1/ip/data_memory_ip/data_memory_ip.xci
# IP: The module: 'data_memory_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado projects/JZ_project_2/JZ_project_2/JZ_project_2.srcs/sources_1/ip/data_memory_ip/data_memory_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_memory_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/vivado projects/JZ_project_2/JZ_project_2/JZ_project_2.srcs/sources_1/ip/data_memory_ip/data_memory_ip.xci
# IP: The module: 'data_memory_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado projects/JZ_project_2/JZ_project_2/JZ_project_2.srcs/sources_1/ip/data_memory_ip/data_memory_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_memory_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
